- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - legacy-labs-ig-cluster-kvm-ubuntu:
            voting: false
        - legacy-labs-ig-cluster-vbox-ubuntu:
            voting: false

