description: Provides input (RST) and output (BASH) based on the configuration below.
rst_path: build/openstack-manuals/doc/install-guide/source
log_file: build/rst2bash.log
bash_path:
    ubuntu: build/scripts/ubuntu
    rdo: build/scripts/rdo
    obs: build/scripts/obs
    debian: build/scripts/debian
rst_files:
    - keystone-install.rst
    # - keystone-openrc.rst
    # - keystone.rst
    - keystone-users.rst
    - keystone-verify.rst
    - launch-instance-cinder.rst
    - launch-instance-networks-provider.rst
    - launch-instance-networks-selfservice.rst
    - launch-instance-provider.rst
    - launch-instance.rst
    - launch-instance-selfservice.rst
    - neutron-compute-install-option1.rst
    - neutron-compute-install-option2.rst
    - neutron-compute-install.rst
    - neutron-concepts.rst
    - neutron-controller-install-option1.rst
    - neutron-controller-install-option2.rst
    - neutron-controller-install.rst
    - neutron-next-steps.rst
    # - neutron.rst
    - neutron-verify-option1.rst
    - neutron-verify-option2.rst
    - neutron-verify.rst
    - nova-compute-install.rst
    - nova-controller-install.rst
    # - nova.rst
    - nova-verify.rst
    # - overview.rst
    - horizon-verify.rst
    - additional-services.rst
    - cinder-backup-install.rst
    - cinder-controller-install.rst
    - cinder-next-steps.rst
    # - cinder.rst
    - cinder-storage-install.rst
    - cinder-verify.rst
    - environment-memcached.rst
    - environment-messaging.rst
    - environment-networking-compute.rst
    - environment-networking-controller.rst
    - environment-networking.rst
    - environment-networking-storage-cinder.rst
    - environment-networking-verify.rst
    - environment-ntp-controller.rst
    - environment-ntp-other.rst
    - environment-ntp.rst
    - environment-ntp-verify.rst
    - environment-packages.rst
    # - environment.rst
    - environment-security.rst
    - environment-sql-database.rst
    - glance-install.rst
    # - glance.rst
    - glance-verify.rst
    - horizon-install.rst
    - horizon-next-steps.rst
    # - horizon.rst
