#!/bin/bash

echo 'WIP: To be implemented.'
echo $@
echo $(whoami)
pip install -r requirements.txt --user ${whoami}
./tools/runparser.sh

labs_path=$(pwd)/build/training-labs/labs
echo $labs_path

function create_default_storagepool() {
    # TODO(dbite): Update this as a feature in training-labs.
    mkdir $HOME/.libvirt_pool
    sudo virsh -c 'qemu:///system'  pool-define-as --name default --type dir --target $HOME/.libvirt_pool
    sudo virsh -c 'qemu:///system' pool-start default
}

if [ "$1" = "kvm" ]; then
    create_default_storagepool
    cd $labs_path
    ./st.py -b cluster -p kvm
fi
